// Build script for tauri-plugin-rsac (ADR-0014).
//
// `tauri_plugin::Builder::new(COMMANDS).build()` autogenerates the
// `allow-<cmd>` / `deny-<cmd>` permission files under permissions/autogenerated/
// for every command listed here. The hand-authored per-command manifests and
// the `[default]` set in permissions/*.toml layer on top of these.
//
// No `global_scope_schema` is declared: this lane has no scope entries (§3.1).

const COMMANDS: &[&str] = &[
    "request_consent",
    "start_capture",
    "stop_capture",
    "list_targets",
    "capabilities",
    "subscribe_meta",
    "subscribe_raw",
];

fn main() {
    tauri_plugin::Builder::new(COMMANDS)
        .android_path("android")
        .ios_path("ios")
        .build();
}
