/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

/**
 * A chunk of captured audio data exposed to JavaScript.
 *
 * Contains interleaved Float32 PCM samples along with format metadata.
 * This is the primary data unit flowing through the JS capture pipeline.
 *
 * `data` is a native JS `Float32Array` carrying the captured `f32` samples
 * directly — there is no `f32` -> `f64` widening on the delivery path, so the
 * values JS observes are bit-for-bit identical to the source samples.
 */
export interface AudioChunk {
  /**
   * Interleaved Float32 PCM audio samples (native `Float32Array`, no
   * precision widening).
   */
  data: Float32Array
  /** Number of audio frames (samples per channel). */
  numFrames: number
  /** Number of audio channels. */
  channels: number
  /** Sample rate in Hz. */
  sampleRate: number
  /** Total number of interleaved samples (num_frames * channels). */
  length: number
  /** Duration of this chunk in seconds. */
  duration: number
  /**
   * Root-mean-square (RMS) level across **all** samples/channels, in linear
   * `0.0..=1.0`. Computed once (alloc-free) by rsac core; `0.0` for silence
   * or an empty chunk, never `NaN`.
   */
  rms: number
  /**
   * Peak (maximum absolute) level across all samples/channels, in linear
   * `0.0..=1.0`. `0.0` for an empty chunk, never `NaN`.
   */
  peak: number
  /**
   * RMS level in dBFS (`20·log10(rms)`). `-Infinity` at silence; `0.0` dBFS
   * is full scale. Computed by rsac core.
   */
  rmsDbfs: number
  /**
   * Peak level in dBFS (`20·log10(peak)`). `-Infinity` at silence; `0.0` dBFS
   * is full scale. Computed by rsac core.
   */
  peakDbfs: number
  /**
   * Per-channel RMS levels, one entry per channel in channel order, linear
   * `0.0..=1.0`. `channelRms[ch]` is the RMS of channel `ch`. Empty when the
   * chunk reports `0` channels. Computed once by rsac core's strided,
   * alloc-free `channel_rms` (a channel with no finite samples is `0.0`).
   */
  channelRms: Array<number>
  /**
   * Per-channel peak levels, one entry per channel in channel order, linear
   * `0.0..=1.0`. `channelPeak[ch]` is the peak of channel `ch`. Empty when
   * the chunk reports `0` channels. Computed once by rsac core's strided,
   * alloc-free `channel_peak`.
   */
  channelPeak: Array<number>
}
/**
 * A point-in-time snapshot of an [`AudioCapture`]'s diagnostic counters.
 *
 * Field-by-field mirror of rsac's `#[non_exhaustive]` `StreamStats`. Counters
 * are `BigInt` (u64) to avoid silent precision loss on long-running captures;
 * `uptimeSecs` and `droppedRatio` are doubles.
 */
export interface JsStreamStats {
  /**
   * Buffers dropped due to ring-buffer overflow (alias of `buffersDropped`,
   * kept for backward compatibility with `overrunCount`).
   */
  overruns: bigint
  /** Cumulative buffers delivered to the consumer (popped off the ring). */
  buffersCaptured: bigint
  /** Cumulative buffers dropped due to ring-buffer overflow. */
  buffersDropped: bigint
  /** Cumulative buffers enqueued by the producer (the OS audio callback). */
  buffersPushed: bigint
  /** How long the stream has been running, in seconds. `0` when not started. */
  uptimeSecs: number
  /**
   * Fraction of accounted-for buffers lost to overflow, in `0.0..=1.0`
   * (`buffersDropped / (buffersCaptured + buffersDropped)`; `0.0` when none).
   */
  droppedRatio: number
  /** Whether the stream is currently capturing. */
  isRunning: boolean
  /**
   * Compact human-readable description of the negotiated format
   * (e.g. `"2ch 48000Hz F32"`); empty before the stream starts.
   */
  formatDescription: string
}
/**
 * A windowed snapshot of an [`AudioCapture`]'s recent backpressure.
 *
 * Field-by-field mirror of rsac's `#[non_exhaustive]` `BackpressureReport`. The
 * `pushed`/`dropped` tallies are `BigInt` (u64) to avoid silent precision loss on
 * long-running captures; `windowSecs` and `dropRate` are doubles, and
 * `isUnderBackpressure` is the legacy consecutive-drop flag carried unchanged.
 */
export interface JsBackpressureReport {
  /**
   * The wall-clock span the `pushed`/`dropped` tallies cover, in seconds. `0`
   * when the span cannot be attributed (no stream / not yet negotiated).
   */
  windowSecs: number
  /** Buffers successfully pushed by the producer within the window. */
  pushed: bigint
  /** Buffers dropped due to ring-buffer overflow within the window. */
  dropped: bigint
  /**
   * Fraction of buffers lost within the window, in `0.0..=1.0`
   * (`dropped / (pushed + dropped)`; `0.0` when nothing has been pushed or
   * dropped). Surfaces sustained partial loss the legacy bool misses.
   */
  dropRate: number
  /**
   * The legacy consecutive-drop backpressure flag, carried unchanged: trips only
   * on a run of consecutive drops and resets on any successful push.
   */
  isUnderBackpressure: boolean
}
/** The negotiated audio delivery format. */
export interface JsAudioFormat {
  /** Samples per second (e.g. 48000). */
  sampleRate: number
  /** Number of interleaved channels (e.g. 2 for stereo). */
  channels: number
  /** Sample format name: one of `"I16"`, `"I24"`, `"I32"`, `"F32"`. */
  sampleFormat: string
}
/** Information about an audio device. */
export interface JsAudioDevice {
  /** Unique platform-specific device identifier. */
  id: string
  /** Human-readable device name. */
  name: string
  /** Whether this is the system default device. */
  isDefault: boolean
}
/**
 * List all available audio devices on the system.
 *
 * Returns an array of device objects with id, name, and isDefault fields.
 * This is an async operation that performs device enumeration on a worker thread.
 */
export declare function listDevices(): Promise<Array<JsAudioDevice>>
/**
 * Get the default audio device.
 *
 * Returns a device object with id, name, and isDefault fields.
 */
export declare function getDefaultDevice(): Promise<JsAudioDevice>
/** Platform capability information. */
export interface JsPlatformCapabilities {
  /** Whether system-wide audio capture is supported. */
  supportsSystemCapture: boolean
  /** Whether per-application audio capture is supported. */
  supportsApplicationCapture: boolean
  /** Whether process-tree audio capture is supported. */
  supportsProcessTreeCapture: boolean
  /** Whether device selection is supported. */
  supportsDeviceSelection: boolean
  /**
   * Whether the backend delivers device hot-plug / default-change
   * notifications.
   */
  supportsDeviceChangeNotifications: boolean
  /**
   * True when starting a capture requires a config-time user-consent
   * artifact (mobile platforms; see docs/MOBILE_BACKEND_DESIGN.md);
   * false on all desktop backends.
   */
  requiresUserConsent: boolean
  /** Maximum number of channels supported. */
  maxChannels: number
  /** Minimum supported sample rate in Hz. */
  minSampleRate: number
  /** Maximum supported sample rate in Hz. */
  maxSampleRate: number
  /** Supported sample formats (short names, e.g. "I16", "F32"). */
  supportedSampleFormats: Array<string>
  /**
   * The config-time sample-rate whitelist the capture constructor accepts —
   * identical on every platform and intentionally narrower than the
   * device-negotiable min/max sample-rate range.
   */
  supportedSampleRates: Array<number>
  /** Name of the audio backend (e.g., "WASAPI", "CoreAudio", "PipeWire"). */
  backendName: string
}
/**
 * Query the audio capabilities of the current platform.
 *
 * Returns information about what capture modes, sample rates, and
 * channel configurations are supported.
 */
export declare function platformCapabilities(): JsPlatformCapabilities
/**
 * An opaque capture target value. Created via static factory methods on this class.
 *
 * Usage from JS/TS:
 * ```js
 * CaptureTarget.systemDefault()
 * CaptureTarget.device("device-id-string")
 * CaptureTarget.application("app-session-id")
 * CaptureTarget.applicationByName("Firefox")
 * CaptureTarget.processTree(12345)
 * ```
 */
export declare class CaptureTarget {
  /** Capture from the system default audio device. */
  static systemDefault(): CaptureTarget
  /** Capture from a specific audio device by ID. */
  static device(deviceId: string): CaptureTarget
  /** Capture audio from a specific application by session ID. */
  static application(appId: string): CaptureTarget
  /** Capture audio from the first application matching the given name. */
  static applicationByName(name: string): CaptureTarget
  /** Capture audio from a process and all its child processes. */
  static processTree(pid: number): CaptureTarget
  /**
   * Parse a capture target from its canonical string form.
   *
   * Accepts the cross-binding grammar (the scheme is case-insensitive):
   * - `"system"` / `"default"` → system default mix
   * - `"device:<id>"` → a specific device (the id may itself contain colons,
   *   e.g. `"device:hw:0,0"`)
   * - `"app:<id>"` → a specific application session
   * - `"name:<name>"` → the first application matching `<name>`
   * - `"tree:<pid>"` / `"pid:<pid>"` → a process and its children
   *
   * Throws a JS `Error` (code `ERR_RSAC_CONFIGURATION`) on an unknown scheme
   * or a non-numeric / out-of-range pid. Never panics.
   *
   * ```js
   * CaptureTarget.parse("system")
   * CaptureTarget.parse("name:Firefox")
   * CaptureTarget.parse("pid:1234")
   * ```
   */
  static parse(spec: string): CaptureTarget
  /** Returns a string description of this capture target. */
  describe(): string
}
export declare class AudioCapture {
  /** Create a new AudioCapture with the system default target and default settings. */
  constructor()
  /**
   * Create a new AudioCapture with a specific target and optional settings.
   *
   * @param target - The capture target (from CaptureTarget static methods).
   * @param sampleRate - Desired sample rate in Hz (default: 48000).
   * @param channels - Desired number of channels (default: 2).
   * @param bufferSize - Desired buffer size in frames (optional).
   */
  static create(target: CaptureTarget, sampleRate?: number | undefined | null, channels?: number | undefined | null, bufferSize?: number | undefined | null): AudioCapture
  /**
   * Start audio capture.
   *
   * If an `onData` callback is registered, a background thread is spawned
   * that reads audio chunks and pushes them to JavaScript via a
   * ThreadsafeFunction.
   */
  start(): void
  /**
   * Stop audio capture and release resources.
   *
   * Active data pump threads are terminated. The callback is preserved
   * and can be reused if a new capture session is started.
   */
  stop(): void
  /** Returns whether the capture is currently running. */
  get isRunning(): boolean
  /**
   * Read a single audio chunk (non-blocking).
   *
   * Returns `null` if no data is currently available.
   * Throws if the capture is not running.
   *
   * Not terminal-observable: this and `read_async` route through rsac's
   * `read_buffer`, which short-circuits to a *recoverable*
   * `StreamReadError` the moment the stream leaves `Running` and never
   * surfaces the terminal `StreamEnded`. The BLOCKING readers
   * (`read_blocking`/`read_blocking_async`) ARE terminal-observable as of
   * rsac-477d, as is the push pump started by `on_data` (terminal reason
   * via `on_end`). A non-blocking pull consumer should treat
   * `stop`/`is_running` as the end-of-stream signal and a thrown read
   * error as retryable.
   */
  read(): AudioChunk | null
  /**
   * Read a single audio chunk, blocking until data is available.
   *
   * WARNING: This blocks the calling thread. In Node.js, prefer
   * `onData()` for push-based streaming or use `read()` in a loop
   * with appropriate yielding.
   *
   * Terminal-observable (rsac-477d): once the stream has ended — after
   * `stop()` or a fatal backend error — this throws the stream's true
   * terminal error (`StreamEnded`) promptly instead of downgrading it to
   * a recoverable "not running" error, matching the C FFI and Go.
   */
  readBlocking(): AudioChunk
  /**
   * Read a single audio chunk asynchronously (non-blocking, off main thread).
   *
   * Returns `null` if no data is currently available.
   * Throws if the capture is not running.
   */
  readAsync(): Promise<AudioChunk | null>
  /**
   * Read a single audio chunk asynchronously, blocking the worker thread
   * until data is available.
   *
   * This is useful for consuming audio in an async loop without busy-spinning.
   *
   * Terminal-observable (rsac-477d): once the stream has ended this
   * rejects with the stream's true terminal error (`StreamEnded`) promptly
   * instead of a recoverable "not running" error — see `readBlocking`.
   */
  readBlockingAsync(): Promise<AudioChunk>
  /**
   * Register a callback for push-based audio data delivery.
   *
   * The callback receives `AudioChunk` objects as audio is captured.
   * This is the most efficient way to consume audio data from Node.js —
   * it uses a ThreadsafeFunction to push data directly from the Rust
   * capture thread to JavaScript.
   *
   * If capture is already running, the data pump starts immediately.
   * If not, it starts when `start()` is called.
   *
   * Only one callback can be active at a time. Calling `onData()` again
   * replaces the previous callback.
   */
  onData(callback: (chunk: AudioChunk) => void): void
  /**
   * Register a callback that fires exactly once when push-based delivery ends,
   * carrying *why* it ended.
   *
   * The data pump started by `onData` ends in one of two ways, and a plain
   * `onData` consumer cannot otherwise distinguish them:
   *
   * - **Terminal (fatal):** the backend stream reached its terminal state
   *   (e.g. `StreamEnded`). The callback's `error` argument is the formatted
   *   terminal `AudioError` message (a non-null string).
   * - **Clean stop:** the pump was torn down by `stop` / `offData`, or the
   *   read mutex was poisoned. The callback's `error` argument is `null`.
   *
   * This is the Node parity for Rust's `subscribe_with_errors` and Go's
   * `StreamWithErrors`: an `onData` consumer registers `onEnd` to learn the
   * terminal reason instead of the pump silently logging it. Registering an
   * `onEnd` callback is optional and independent of `onData`.
   *
   * The registration persists across multiple `start`/`stop` sessions on the
   * same `AudioCapture`, exactly like `onData`: it fires once per session (at
   * each pump run's end) and stays armed for the next session. The pump fires a
   * *clone* and leaves the registered callback in place; it is cleared only by
   * `offEnd` or replaced by a later `onEnd` call. A recoverable hiccup never
   * fires it — only the single terminal end (fatal) or a clean stop does.
   */
  onEnd(callback: (error: string | null) => void): void
  /**
   * Remove the registered data callback.
   *
   * Stops the data pump thread if running. The terminal-observability
   * callback registered via `onEnd` is left registered for a later session;
   * use `offEnd` to clear it.
   */
  offData(): void
  /**
   * Remove the registered terminal-observability callback (see `onEnd`).
   *
   * This is the *only* way to clear an `onEnd` registration — unlike a
   * one-shot, the pump leaves it armed across sessions. After this, the pump's
   * end is no longer reported to JS; a *fatal* terminal still falls back to a
   * (throttled) stderr log line, while a clean stop ends silently. Does not
   * stop the pump.
   */
  offEnd(): void
  /**
   * Returns the number of audio buffers dropped due to ring buffer overflow.
   *
   * A non-zero value means the JavaScript consumer is not keeping up with
   * the audio producer.
   */
  get overrunCount(): number
  /**
   * Returns a point-in-time snapshot of the stream's diagnostic counters.
   *
   * Maps rsac's `#[non_exhaustive]` `StreamStats` field-by-field into a plain
   * JS object (see `StreamStats` in the type definitions). All counters are
   * read with cheap relaxed loads on this non-real-time query path — calling
   * this never allocates on or blocks the OS audio callback thread.
   *
   * Before `start()` (or after `stop()`) this returns a zeroed snapshot with
   * `isRunning === false` and `uptimeSecs === 0`.
   */
  streamStats(): JsStreamStats
  /**
   * Returns a windowed snapshot of the stream's recent backpressure.
   *
   * Maps rsac's `#[non_exhaustive]` `BackpressureReport` field-by-field into a
   * plain JS object (see `BackpressureReport` in the type definitions). Unlike
   * the all-or-nothing `isUnderBackpressure` flag — which trips only on a run of
   * *consecutive* drops and resets on any successful push — `dropRate` is
   * computed over a recent window of push activity, so a sustained partial loss
   * (e.g. a steady 1-in-3 drop pattern) is visible. The legacy bool is carried
   * through unchanged. Reading these counters never allocates on or blocks the
   * OS audio callback thread.
   *
   * Before `start()` (or after `stop()`) this returns the all-zero default with
   * `windowSecs === 0`, `dropRate === 0.0`, and `isUnderBackpressure === false`.
   */
  backpressureReport(): JsBackpressureReport
  /**
   * The negotiated *delivery* format the backend actually produces, or `null`
   * before `start()` creates a stream.
   *
   * This is the authoritative format published by the bridge once a backend
   * records it; it may differ from the requested settings when the device
   * forced a negotiation. Reading it does not allocate or lock the data plane.
   */
  get format(): JsAudioFormat | null
}
