#ifndef RSAC_H
#define RSAC_H

/* Warning: this file is autogenerated by cbindgen. Do not modify manually. */

#include <stdarg.h>
#include <stdbool.h>
#include <stdint.h>
#include <stdlib.h>

/**
 * Device kind for enumeration.
 */
typedef enum rsac_device_kind_t {
    RSAC_DEVICE_INPUT = 0,
    RSAC_DEVICE_OUTPUT = 1,
} rsac_device_kind_t;

/**
 * Error codes returned by all rsac FFI functions.
 */
typedef enum rsac_error_t {
    /**
     * Operation succeeded.
     */
    RSAC_OK = 0,
    /**
     * A null pointer was passed where a valid pointer was expected.
     */
    RSAC_ERROR_NULL_POINTER = 1,
    /**
     * Invalid parameter value.
     */
    RSAC_ERROR_INVALID_PARAMETER = 2,
    /**
     * The requested device was not found.
     */
    RSAC_ERROR_DEVICE_NOT_FOUND = 3,
    /**
     * The requested feature is not supported on this platform.
     */
    RSAC_ERROR_PLATFORM_NOT_SUPPORTED = 4,
    /**
     * Failed to create or start an audio stream.
     */
    RSAC_ERROR_STREAM_FAILED = 5,
    /**
     * Failed to read audio data from the stream.
     */
    RSAC_ERROR_STREAM_READ = 6,
    /**
     * A configuration error occurred.
     */
    RSAC_ERROR_CONFIGURATION = 7,
    /**
     * The target application was not found.
     */
    RSAC_ERROR_APPLICATION_NOT_FOUND = 8,
    /**
     * A backend-specific error occurred.
     */
    RSAC_ERROR_BACKEND = 9,
    /**
     * Permission denied.
     */
    RSAC_ERROR_PERMISSION_DENIED = 10,
    /**
     * An operation timed out.
     */
    RSAC_ERROR_TIMEOUT = 11,
    /**
     * An internal or unknown error occurred.
     */
    RSAC_ERROR_INTERNAL = 12,
    /**
     * A Rust panic was caught (should not happen in normal use).
     */
    RSAC_ERROR_PANIC = 99,
} rsac_error_t;

#if defined(RSAC_FEATURE_COMPOSE)
/**
 * How a composition group's sources map onto the composed output channels.
 * Mirrors [`rsac::compose::GroupLayout`].
 */
typedef enum rsac_group_layout_t {
#if defined(RSAC_FEATURE_COMPOSE)
    /**
     * Fold every source in the group to mono and gain-weighted-sum them into
     * **one** output channel.
     */
    RSAC_GROUP_LAYOUT_MONO = 0,
#endif
#if defined(RSAC_FEATURE_COMPOSE)
    /**
     * Fold every source to stereo and sum into **two** output channels
     * (the default layout of a new group).
     */
    RSAC_GROUP_LAYOUT_STEREO = 1,
#endif
#if defined(RSAC_FEATURE_COMPOSE)
    /**
     * Pass the group's **single** source through with its native channel
     * count (a keep-channels group must contain exactly one source).
     */
    RSAC_GROUP_LAYOUT_KEEP_CHANNELS = 2,
#endif
} rsac_group_layout_t;
#endif

/**
 * Sample wire/storage format, mirroring [`rsac::SampleFormat`].
 *
 * All audio data is delivered as interleaved `f32` regardless of this value;
 * it describes the negotiated wire format the backend reports.
 */
typedef enum rsac_sample_format_t {
    /**
     * Signed 16-bit integer.
     */
    RSAC_SAMPLE_FORMAT_I16 = 0,
    /**
     * Signed 24-bit integer (packed in a 32-bit container).
     */
    RSAC_SAMPLE_FORMAT_I24 = 1,
    /**
     * Signed 32-bit integer.
     */
    RSAC_SAMPLE_FORMAT_I32 = 2,
    /**
     * 32-bit IEEE 754 floating-point (the library's internal standard).
     */
    RSAC_SAMPLE_FORMAT_F32 = 3,
} rsac_sample_format_t;

/**
 * Opaque handle to an `AudioBuffer`.
 */
typedef struct RsacAudioBuffer RsacAudioBuffer;

/**
 * Opaque handle to an `AudioCaptureBuilder`.
 */
typedef struct RsacBuilder RsacBuilder;

/**
 * Opaque handle to platform capabilities.
 */
typedef struct RsacCapabilities RsacCapabilities;

/**
 * Opaque handle to an `AudioCapture` session.
 */
typedef struct RsacCapture RsacCapture;

#if defined(RSAC_FEATURE_COMPOSE)
/**
 * Opaque handle to a `Composition` session.
 */
typedef struct RsacComposition RsacComposition;
#endif

#if defined(RSAC_FEATURE_COMPOSE)
/**
 * Opaque handle to a `CompositionBuilder`.
 */
typedef struct RsacCompositionBuilder RsacCompositionBuilder;
#endif

/**
 * Opaque handle to a single audio device.
 */
typedef struct RsacDevice RsacDevice;

/**
 * Opaque handle to a device enumerator.
 */
typedef struct RsacDeviceEnumerator RsacDeviceEnumerator;

/**
 * Opaque handle to a list of audio devices.
 */
typedef struct RsacDeviceList RsacDeviceList;

#if defined(RSAC_FEATURE_COMPOSE)
/**
 * Opaque handle to a composition `Group` under construction.
 */
typedef struct RsacGroup RsacGroup;
#endif

/**
 * A point-in-time snapshot of a capture's stream statistics.
 *
 * Filled by [`rsac_capture_stream_stats`] from [`AudioCapture::stream_stats`].
 * This is a plain C-ABI value type (no heap, no free required). It mirrors the
 * counters in [`rsac::StreamStats`]; `is_running` is `1` when capturing, else `0`.
 *
 * When no stream has been created (before start, or after stop) every counter
 * is `0`, `uptime_secs` is `0.0`, and `is_running` is `0`.
 */
typedef struct RsacStreamStats {
    /**
     * Buffers delivered to the consumer (popped off the ring) since start.
     */
    uint64_t buffers_captured;
    /**
     * Buffers dropped due to ring-buffer overflow since start.
     */
    uint64_t buffers_dropped;
    /**
     * Buffers enqueued by the producer (the OS audio callback) since start.
     */
    uint64_t buffers_pushed;
    /**
     * Ring-buffer overruns. Equal to `buffers_dropped` (retained alias).
     */
    uint64_t overruns;
    /**
     * How long the stream has been running, in seconds. `0.0` when not started.
     */
    double uptime_secs;
    /**
     * Fraction of accounted-for buffers lost to overflow, in `0.0..=1.0`.
     */
    double dropped_ratio;
    /**
     * `1` if the stream is currently capturing, `0` otherwise.
     */
    int32_t is_running;
} RsacStreamStats;

/**
 * A point-in-time **windowed** backpressure snapshot.
 *
 * Filled by [`rsac_capture_backpressure_report`] from
 * [`AudioCapture::backpressure_report`]. Plain C-ABI value type (no heap, no
 * free required). Unlike the lifetime counters in [`RsacStreamStats`], the
 * `pushed`/`dropped` here cover a bounded recent window, so `drop_rate`
 * surfaces a sustained 1-in-N loss the consecutive-drop flag resets away.
 *
 * When no stream has been created every field is `0`/`0.0`/`false`.
 * `window_secs` is `0.0` when the span cannot be attributed (unknown buffer
 * size or sample rate); the `pushed`/`dropped` tallies are still valid.
 */
typedef struct RsacBackpressureReport {
    /**
     * Wall-clock span the tallies cover, in seconds. `0.0` when unattributed.
     */
    double window_secs;
    /**
     * Buffers successfully pushed by the producer within the window.
     */
    uint64_t pushed;
    /**
     * Buffers dropped due to ring-buffer overflow within the window.
     */
    uint64_t dropped;
    /**
     * Fraction of buffers lost within the window, in `0.0..=1.0`.
     */
    double drop_rate;
    /**
     * `1` if the legacy consecutive-drop flag is set, `0` otherwise.
     */
    int32_t is_under_backpressure;
} RsacBackpressureReport;

/**
 * A point-in-time snapshot of a capture's negotiated delivery format.
 *
 * Filled by [`rsac_capture_format`] from [`AudioCapture::format`]. Plain C-ABI
 * value type (no heap, no free required).
 */
typedef struct RsacAudioFormat {
    /**
     * Samples per second (e.g. 44100, 48000).
     */
    uint32_t sample_rate;
    /**
     * Number of audio channels (e.g. 1 mono, 2 stereo).
     */
    uint16_t channels;
    /**
     * The negotiated sample wire format.
     */
    enum rsac_sample_format_t sample_format;
    /**
     * Bits per sample for `sample_format` (16, 24, or 32).
     */
    uint16_t bits_per_sample;
} RsacAudioFormat;

/**
 * C callback type for audio data.
 *
 * Called with:
 * - `buffer_data`: pointer to interleaved f32 sample data
 * - `num_samples`: total number of f32 values in buffer_data
 * - `channels`: number of audio channels
 * - `sample_rate`: sample rate in Hz
 * - `user_data`: opaque pointer passed to `rsac_capture_set_callback`
 */
typedef void (*rsac_audio_callback_t)(const float *buffer_data,
                                      uintptr_t num_samples,
                                      uint16_t channels,
                                      uint32_t sample_rate,
                                      void *user_data);

#if defined(RSAC_FEATURE_COMPOSE)
/**
 * A point-in-time snapshot of a running composition's counters.
 *
 * Filled by [`rsac_composition_stats`] from `Composition::stats`. Plain C-ABI
 * value type (no heap, no free required). Before [`rsac_composition_start`]
 * succeeds every field is `0` (the compositor engine does not exist yet).
 */
typedef struct RsacCompositionStats {
    /**
     * Composed buffers (ticks) emitted so far.
     */
    uint64_t ticks;
    /**
     * Ticks emitted by the wall-clock stall fallback (master had no data).
     */
    uint64_t fallback_ticks;
    /**
     * Number of composed sources, in flat declaration order. `0` before
     * start. Valid indices for the per-source accessors are
     * `0..num_sources`.
     */
    uintptr_t num_sources;
} RsacCompositionStats;
#endif

#if defined(RSAC_FEATURE_COMPOSE)
/**
 * A point-in-time snapshot of one composed source's counters.
 *
 * Filled by [`rsac_composition_source_stats`]. Plain C-ABI value type (no
 * heap, no free required). The source's group name and target string are
 * available via [`rsac_composition_source_group`] and
 * [`rsac_composition_source_target`].
 */
typedef struct RsacSourceStats {
    /**
     * Buffers received from the inner capture so far.
     */
    uint64_t buffers_received;
    /**
     * Frames of silence inserted because the source was behind at tick time.
     */
    uint64_t padded_frames;
    /**
     * Frames trimmed because the source drifted past the buffering bound.
     */
    uint64_t trimmed_frames;
    /**
     * `1` if this source is being resampled to the session rate, else `0`.
     */
    int32_t resampling;
    /**
     * `1` if the source's stream has ended, else `0`.
     */
    int32_t ended;
} RsacSourceStats;
#endif

/**
 * Returns a pointer to the last error message for the current thread.
 *
 * The returned string is valid until the next rsac FFI call on this thread.
 * Returns an empty string if no error has occurred.
 */
 const char *rsac_error_message(void) ;

/**
 * Creates a new `AudioCaptureBuilder` with default settings.
 *
 * Returns a handle that must be freed with `rsac_builder_free()`.
 * On failure, `*out` is set to null.
 */
 enum rsac_error_t rsac_builder_new(struct RsacBuilder **out) ;

/**
 * Frees a builder handle. No-op if null.
 */
 void rsac_builder_free(struct RsacBuilder *builder) ;

/**
 * Sets the capture target to system default audio.
 */
 enum rsac_error_t rsac_builder_set_target_system(struct RsacBuilder *builder) ;

/**
 * Sets the capture target to a specific device by ID.
 */

enum rsac_error_t rsac_builder_set_target_device(struct RsacBuilder *builder,
                                                 const char *device_id)
;

/**
 * Sets the capture target to an application by name.
 */

enum rsac_error_t rsac_builder_set_target_app_by_name(struct RsacBuilder *builder,
                                                      const char *app_name)
;

/**
 * Sets the capture target to an application by ID.
 */

enum rsac_error_t rsac_builder_set_target_app_by_id(struct RsacBuilder *builder,
                                                    const char *app_id)
;

/**
 * Sets the capture target to a process tree by PID.
 */
 enum rsac_error_t rsac_builder_set_target_process_tree(struct RsacBuilder *builder, uint32_t pid) ;

/**
 * Sets the capture target by parsing a canonical target string.
 *
 * `spec` uses the [`CaptureTarget`] string grammar (case-insensitive scheme):
 * `system`, `device:<id>`, `app:<pid-or-id>`, `name:<name>`, or `tree:<pid>`.
 * Parsing goes through `CaptureTarget::from_str` (the same path
 * [`AudioCaptureBuilder::target_str`] uses), so it round-trips with
 * [`rsac::CaptureTarget`]'s `Display`.
 *
 * A malformed string is reported as `RSAC_ERROR_INVALID_PARAMETER` and the
 * builder's existing target is left unchanged (parse-then-commit). This is a
 * convenience over the typed `rsac_builder_set_target_*` setters, which remain
 * available.
 *
 * Returns `RSAC_ERROR_NULL_POINTER` if `builder` or `spec` is null, and
 * `RSAC_ERROR_INVALID_PARAMETER` if `spec` is not valid UTF-8 or not a valid
 * target string.
 */
 enum rsac_error_t rsac_builder_set_target_str(struct RsacBuilder *builder, const char *spec) ;

/**
 * Sets the desired sample rate in Hz.
 */
 enum rsac_error_t rsac_builder_set_sample_rate(struct RsacBuilder *builder, uint32_t sample_rate) ;

/**
 * Sets the desired number of audio channels.
 */
 enum rsac_error_t rsac_builder_set_channels(struct RsacBuilder *builder, uint16_t channels) ;

/**
 * Builds an `AudioCapture` from the builder configuration.
 *
 * On success, `*out` receives the capture handle. The builder is consumed
 * and freed. On failure, `*out` is null and the builder is also consumed
 * (Rust ownership semantics — create a new builder to retry).
 */
 enum rsac_error_t rsac_builder_build(struct RsacBuilder *builder, struct RsacCapture **out) ;

/**
 * Starts the audio capture stream.
 */
 enum rsac_error_t rsac_capture_start(struct RsacCapture *capture) ;

/**
 * Stops the audio capture stream.
 */
 enum rsac_error_t rsac_capture_stop(struct RsacCapture *capture) ;

/**
 * Returns 1 if the capture stream is currently running, 0 otherwise.
 * Returns -1 if the capture handle is null.
 */
 int32_t rsac_capture_is_running(const struct RsacCapture *capture) ;

/**
 * Returns the number of ring buffer overruns (dropped buffers).
 * Returns 0 if the capture handle is null or no stream exists.
 */
 uint64_t rsac_capture_overrun_count(const struct RsacCapture *capture) ;

/**
 * Fills `*out` with a point-in-time [`RsacStreamStats`] snapshot of the capture.
 *
 * The snapshot bundles the bridge's diagnostic counters with the running state,
 * uptime, and overflow ratio. Reading it never allocates on or blocks the OS
 * audio callback thread.
 *
 * When no stream has been created (before start, or after stop), `*out` is
 * filled with an all-zero snapshot (`is_running == 0`).
 *
 * Returns `RSAC_ERROR_NULL_POINTER` if `capture` or `out` is null; otherwise
 * `RSAC_OK`. `out` is an out-parameter, not a handle: there is nothing to free.
 */

enum rsac_error_t rsac_capture_stream_stats(const struct RsacCapture *capture,
                                            struct RsacStreamStats *out)
;

/**
 * Fills `*out` with a point-in-time **windowed** [`RsacBackpressureReport`].
 *
 * Unlike [`rsac_capture_stream_stats`]' lifetime counters, this reports a
 * bounded recent window, so `drop_rate` reflects a sustained 1-in-N loss that
 * the consecutive-drop flag resets away. Reading it never allocates on or
 * blocks the OS audio callback thread.
 *
 * When no stream has been created, `*out` is filled with an all-zero report.
 *
 * Returns `RSAC_ERROR_NULL_POINTER` if `capture` or `out` is null; otherwise
 * `RSAC_OK`. `out` is an out-parameter, not a handle: there is nothing to free.
 */

enum rsac_error_t rsac_capture_backpressure_report(const struct RsacCapture *capture,
                                                   struct RsacBackpressureReport *out)
;

/**
 * Fills `*out` with the negotiated delivery [`RsacAudioFormat`] of the capture.
 *
 * This is the format the backend actually produces, atomically published by the
 * bridge once a stream is created. Returns `RSAC_ERROR_STREAM_FAILED` when no
 * stream has been created yet (before start, or after stop), leaving `*out`
 * untouched — call this only on a started capture, or after checking
 * [`rsac_capture_is_running`].
 *
 * Returns `RSAC_ERROR_NULL_POINTER` if `capture` or `out` is null. `out` is an
 * out-parameter, not a handle: there is nothing to free.
 */

enum rsac_error_t rsac_capture_format(const struct RsacCapture *capture,
                                      struct RsacAudioFormat *out)
;

/**
 * Frees a capture handle. Stops the stream if running. No-op if null.
 */
 void rsac_capture_free(struct RsacCapture *capture) ;

/**
 * Attempts a non-blocking read of audio data.
 *
 * On success with data available, `*out` receives a buffer handle.
 * On success with no data available, `*out` is set to null and RSAC_OK is returned.
 * The buffer must be freed with `rsac_audio_buffer_free()`.
 */

enum rsac_error_t rsac_capture_try_read(const struct RsacCapture *capture,
                                        struct RsacAudioBuffer **out)
;

/**
 * Reads audio data, blocking until data is available.
 *
 * On success, `*out` receives a buffer handle that must be freed
 * with `rsac_audio_buffer_free()`.
 */

enum rsac_error_t rsac_capture_read(const struct RsacCapture *capture,
                                    struct RsacAudioBuffer **out)
;

/**
 * Best-effort request to stop the capture, used to **unblock a parked
 * [`rsac_capture_read`]**.
 *
 * Transitions the underlying stream toward its terminal state so a thread
 * blocked in `rsac_capture_read` returns promptly (with a terminal stream
 * error) instead of waiting out the blocking-read timeout. It is idempotent
 * and a no-op when no stream has been created (or it is already stopped).
 *
 * # Safety / ordering
 *
 * - Takes `*const RsacCapture`: it is **safe to call concurrently with an
 *   in-flight `rsac_capture_read` / `rsac_capture_try_read`** to unblock it
 *   (it forms no `&mut` alias to the capture).
 * - It is **NOT** safe to call concurrently with `rsac_capture_free`. The
 *   caller must order `request_stop` + a drain of in-flight reads **before**
 *   freeing the handle (the sqlite3_interrupt contract).
 *
 * Returns `RSAC_ERROR_NULL_POINTER` if `capture` is null, else `RSAC_OK`.
 */
 enum rsac_error_t rsac_capture_request_stop(const struct RsacCapture *capture) ;

/**
 * Sets a callback for push-based audio delivery.
 *
 * The callback is invoked on a background thread for each captured audio buffer.
 * Must be called before `rsac_capture_start()`.
 *
 * Pass `callback = NULL` to clear the callback.
 *
 * # Safety
 *
 * - `user_data` is passed through to the callback unchanged; the caller is
 *   responsible for its lifetime and thread safety.
 * - The callback must not call any rsac functions (to avoid deadlocks).
 */

enum rsac_error_t rsac_capture_set_callback(struct RsacCapture *capture,
                                            rsac_audio_callback_t callback,
                                            void *user_data)
;

/**
 * Returns a pointer to the interleaved f32 sample data.
 *
 * The pointer is valid until the buffer is freed. Returns null if the buffer is null.
 */
 const float *rsac_audio_buffer_data(const struct RsacAudioBuffer *buffer) ;

/**
 * Returns the total number of f32 samples in the buffer (all channels).
 * Returns 0 if the buffer is null.
 */
 uintptr_t rsac_audio_buffer_len(const struct RsacAudioBuffer *buffer) ;

/**
 * Returns the number of audio frames in the buffer.
 * Returns 0 if the buffer is null.
 */
 uintptr_t rsac_audio_buffer_num_frames(const struct RsacAudioBuffer *buffer) ;

/**
 * Returns the number of channels in the buffer.
 * Returns 0 if the buffer is null.
 */
 uint16_t rsac_audio_buffer_channels(const struct RsacAudioBuffer *buffer) ;

/**
 * Returns the sample rate of the buffer in Hz.
 * Returns 0 if the buffer is null.
 */
 uint32_t rsac_audio_buffer_sample_rate(const struct RsacAudioBuffer *buffer) ;

/**
 * Returns the root-mean-square (RMS) level across all samples/channels.
 *
 * Wraps [`rsac::AudioBuffer::rms`]: `sqrt(mean(xᵢ²))` over the interleaved
 * data. Non-finite samples are skipped; a silent or empty buffer yields `0.0`
 * (never `NaN`). Read-only measurement — no allocation, RT-callback safe.
 * Returns `0.0` if the buffer is null.
 */
 float rsac_audio_buffer_rms(const struct RsacAudioBuffer *buffer) ;

/**
 * Returns the peak (maximum absolute) level across all samples/channels.
 *
 * Wraps [`rsac::AudioBuffer::peak`]: `max(|xᵢ|)`. Non-finite samples are
 * skipped; a silent or empty buffer yields `0.0` (never `NaN`). Read-only
 * measurement — no allocation. Returns `0.0` if the buffer is null.
 */
 float rsac_audio_buffer_peak(const struct RsacAudioBuffer *buffer) ;

/**
 * Returns the RMS level in dBFS: `20 · log10(rms())`.
 *
 * Wraps [`rsac::AudioBuffer::rms_dbfs`]. Returns negative infinity for silence
 * or an empty buffer, and **also** negative infinity if the buffer is null
 * (there is no level to report). Full scale (RMS `1.0`) maps to `0.0` dBFS.
 */
 float rsac_audio_buffer_rms_dbfs(const struct RsacAudioBuffer *buffer) ;

/**
 * Returns the peak level in dBFS: `20 · log10(peak())`.
 *
 * Wraps [`rsac::AudioBuffer::peak_dbfs`]. Returns negative infinity for silence
 * or an empty buffer, and **also** negative infinity if the buffer is null.
 * A full-scale signal (peak `1.0`) maps to `0.0` dBFS.
 */
 float rsac_audio_buffer_peak_dbfs(const struct RsacAudioBuffer *buffer) ;

/**
 * Frees an audio buffer handle. No-op if null.
 */
 void rsac_audio_buffer_free(struct RsacAudioBuffer *buffer) ;

/**
 * Creates a new device enumerator.
 *
 * On success, `*out` receives the enumerator handle. Must be freed with
 * `rsac_device_enumerator_free()`.
 */
 enum rsac_error_t rsac_device_enumerator_new(struct RsacDeviceEnumerator **out) ;

/**
 * Frees a device enumerator handle. No-op if null.
 */
 void rsac_device_enumerator_free(struct RsacDeviceEnumerator *enumerator) ;

/**
 * Enumerates all audio devices into a device list.
 *
 * On success, `*out` receives the device list handle. Must be freed with
 * `rsac_device_list_free()`.
 */

enum rsac_error_t rsac_device_list_new(const struct RsacDeviceEnumerator *enumerator,
                                       struct RsacDeviceList **out)
;

/**
 * Returns the number of devices in the list.
 * Returns 0 if the list is null.
 */
 uintptr_t rsac_device_list_count(const struct RsacDeviceList *list) ;

/**
 * Gets a device from the list by index.
 *
 * On success, `*out` receives a device handle that must be freed with
 * `rsac_device_free()`. Returns an error if the index is out of bounds.
 *
 * The returned device is a snapshot — it carries the device's name, ID,
 * and default status, but cannot be used to create streams directly.
 */

enum rsac_error_t rsac_device_list_get(const struct RsacDeviceList *list,
                                       uintptr_t index,
                                       struct RsacDevice **out)
;

/**
 * Frees a device list handle. No-op if null.
 */
 void rsac_device_list_free(struct RsacDeviceList *list) ;

/**
 * Gets the default audio device.
 *
 * On success, `*out` receives a device handle that must be freed with
 * `rsac_device_free()`.
 */

enum rsac_error_t rsac_default_device(const struct RsacDeviceEnumerator *enumerator,
                                      enum rsac_device_kind_t kind,
                                      struct RsacDevice **out)
;

/**
 * Returns the device name as a C string.
 *
 * The returned pointer is valid until the next call to `rsac_device_name()` or
 * `rsac_device_id()` on the same thread. Returns null if the device handle is null.
 */
 const char *rsac_device_name(const struct RsacDevice *device) ;

/**
 * Returns the device ID as a C string.
 *
 * The returned pointer is valid until the next call to `rsac_device_name()` or
 * `rsac_device_id()` on the same thread. Returns null if the device handle is null.
 */
 const char *rsac_device_id(const struct RsacDevice *device) ;

/**
 * Returns 1 if the device is the system default, 0 otherwise.
 * Returns -1 if the device handle is null.
 */
 int32_t rsac_device_is_default(const struct RsacDevice *device) ;

/**
 * Frees a device handle. No-op if null.
 */
 void rsac_device_free(struct RsacDevice *device) ;

/**
 * Queries platform capabilities.
 *
 * On success, `*out` receives a capabilities handle. Must be freed with
 * `rsac_capabilities_free()`.
 */
 enum rsac_error_t rsac_capabilities_query(struct RsacCapabilities **out) ;

/**
 * Frees a capabilities handle. No-op if null.
 */
 void rsac_capabilities_free(struct RsacCapabilities *caps) ;

/**
 * Returns 1 if system capture is supported, 0 otherwise.
 * Returns -1 if the handle is null.
 */
 int32_t rsac_capabilities_supports_system_capture(const struct RsacCapabilities *caps) ;

/**
 * Returns 1 if application capture is supported, 0 otherwise.
 * Returns -1 if the handle is null.
 */
 int32_t rsac_capabilities_supports_app_capture(const struct RsacCapabilities *caps) ;

/**
 * Returns 1 if process tree capture is supported, 0 otherwise.
 * Returns -1 if the handle is null.
 */
 int32_t rsac_capabilities_supports_process_tree(const struct RsacCapabilities *caps) ;

/**
 * Returns 1 if device selection is supported, 0 otherwise.
 * Returns -1 if the handle is null.
 */
 int32_t rsac_capabilities_supports_device_selection(const struct RsacCapabilities *caps) ;

/**
 * Returns the maximum number of channels supported.
 * Returns 0 if the handle is null.
 */
 uint16_t rsac_capabilities_max_channels(const struct RsacCapabilities *caps) ;

/**
 * Returns the backend name (e.g., "WASAPI", "CoreAudio", "PipeWire") as a C string.
 *
 * The returned pointer is valid until the next call to `rsac_capabilities_backend_name()`
 * on the same thread. Returns null if the handle is null.
 */
 const char *rsac_capabilities_backend_name(const struct RsacCapabilities *caps) ;

/**
 * Returns the rsac-ffi version string.
 *
 * The returned pointer is a static string valid for the lifetime of the library.
 */
 const char *rsac_version(void) ;

#if defined(RSAC_FEATURE_COMPOSE)
/**
 * Creates a new composition group with the given name and the default
 * stereo layout (`RSAC_GROUP_LAYOUT_STEREO`).
 *
 * The name must be unique within a composition and non-empty (both enforced
 * at [`rsac_composition_builder_build`], not here). On success the caller
 * owns the handle and must either hand it to
 * [`rsac_composition_builder_add_group`] (which consumes it) or free it with
 * [`rsac_group_free`].
 *
 * Returns `RSAC_ERROR_NULL_POINTER` if `name` or `out` is null, and
 * `RSAC_ERROR_INVALID_PARAMETER` if `name` is not valid UTF-8.
 */
 enum rsac_error_t rsac_group_new(const char *name, struct RsacGroup **out) ;
#endif

#if defined(RSAC_FEATURE_COMPOSE)
/**
 * Frees a group handle. No-op if null.
 *
 * Only call this on a group that was **not** consumed by a successful
 * [`rsac_composition_builder_add_group`].
 */
 void rsac_group_free(struct RsacGroup *group) ;
#endif

#if defined(RSAC_FEATURE_COMPOSE)
/**
 * Sets the group's layout (how its sources map onto output channels).
 *
 * A `RSAC_GROUP_LAYOUT_KEEP_CHANNELS` group must contain exactly one source;
 * that arity is enforced at [`rsac_composition_builder_build`].
 *
 * Returns `RSAC_ERROR_NULL_POINTER` if `group` is null.
 */
 enum rsac_error_t rsac_group_set_layout(struct RsacGroup *group, enum rsac_group_layout_t layout) ;
#endif

#if defined(RSAC_FEATURE_COMPOSE)
/**
 * Adds a capture source to the group with unit gain (1.0).
 *
 * `spec` uses the same `CaptureTarget` string grammar as
 * `rsac_builder_set_target_str()` (case-insensitive scheme): `system`,
 * `device:<id>`, `app:<pid-or-id>`, `name:<name>`, or `tree:<pid>`.
 *
 * Returns `RSAC_ERROR_NULL_POINTER` if `group` or `spec` is null, and
 * `RSAC_ERROR_INVALID_PARAMETER` if `spec` is not valid UTF-8 or not a valid
 * target string (the group is unchanged on error — parse-then-commit).
 */
 enum rsac_error_t rsac_group_add_source(struct RsacGroup *group, const char *spec) ;
#endif

#if defined(RSAC_FEATURE_COMPOSE)
/**
 * Adds a capture source to the group with an explicit linear gain applied
 * during mixdown (1.0 = unity).
 *
 * `spec` follows the same grammar as `rsac_group_add_source()`. The gain must
 * be finite and >= 0; an invalid gain is rejected **eagerly** here with
 * `RSAC_ERROR_INVALID_PARAMETER` (the same values would also be rejected at
 * [`rsac_composition_builder_build`], but failing at the call site gives a
 * precise diagnostic).
 *
 * Returns `RSAC_ERROR_NULL_POINTER` if `group` or `spec` is null, and
 * `RSAC_ERROR_INVALID_PARAMETER` for an invalid `spec` or gain (the group is
 * unchanged on error).
 */

enum rsac_error_t rsac_group_add_source_with_gain(struct RsacGroup *group,
                                                  const char *spec,
                                                  float gain)
;
#endif

#if defined(RSAC_FEATURE_COMPOSE)
/**
 * Creates a new `CompositionBuilder` with default settings (48 kHz session
 * rate, no output clamping, no groups).
 *
 * Returns a handle that must be freed with
 * [`rsac_composition_builder_free`] (or consumed by
 * [`rsac_composition_builder_build`]).
 */
 enum rsac_error_t rsac_composition_builder_new(struct RsacCompositionBuilder **out) ;
#endif

#if defined(RSAC_FEATURE_COMPOSE)
/**
 * Frees a composition builder handle. No-op if null.
 *
 * Only call this on a builder that was **not** consumed by
 * [`rsac_composition_builder_build`].
 */
 void rsac_composition_builder_free(struct RsacCompositionBuilder *builder) ;
#endif

#if defined(RSAC_FEATURE_COMPOSE)
/**
 * Sets the session sample rate in Hz (default 48000). Sources delivering a
 * different rate are resampled. An unsupported rate is rejected at
 * [`rsac_composition_builder_build`].
 */

enum rsac_error_t rsac_composition_builder_set_sample_rate(struct RsacCompositionBuilder *builder,
                                                           uint32_t sample_rate)
;
#endif

#if defined(RSAC_FEATURE_COMPOSE)
/**
 * Enables (`clamp` nonzero) or disables (`clamp` 0) saturating output
 * clamping to `[-1.0, 1.0]` after summation. Default off: plain summation may
 * exceed unity, which is legal for f32 pipelines.
 */

enum rsac_error_t rsac_composition_builder_set_clamp_output(struct RsacCompositionBuilder *builder,
                                                            int32_t clamp)
;
#endif

#if defined(RSAC_FEATURE_COMPOSE)
/**
 * Appends a group to the composition. Groups contribute output channels in
 * the order they are added.
 *
 * On success (`RSAC_OK`) **the group handle is consumed**: do not use or
 * free it afterwards. On any error the group is untouched and the caller
 * still owns it (and must eventually call [`rsac_group_free`]).
 *
 * Returns `RSAC_ERROR_NULL_POINTER` if `builder` or `group` is null.
 */

enum rsac_error_t rsac_composition_builder_add_group(struct RsacCompositionBuilder *builder,
                                                     struct RsacGroup *group)
;
#endif

#if defined(RSAC_FEATURE_COMPOSE)
/**
 * Validates the configuration and builds a (not yet started)
 * `Composition`.
 *
 * **The builder is always consumed** — on failure too (Rust ownership
 * semantics; create a new builder to retry), matching `rsac_builder_build()`.
 * No devices are touched here; inner captures are created and started by
 * [`rsac_composition_start`]. On success `*out` receives the composition
 * handle, which must be freed with [`rsac_composition_free`]. On failure
 * `*out` is null.
 *
 * Validation failures map to `RSAC_ERROR_CONFIGURATION` (no groups, empty
 * group, duplicate/empty group name, keep-channels group without exactly one
 * source, invalid gain, too many sources or channels),
 * `RSAC_ERROR_INVALID_PARAMETER` (unsupported session sample rate), or
 * `RSAC_ERROR_PLATFORM_NOT_SUPPORTED` (a target this platform cannot
 * capture). Call `rsac_error_message()` for details.
 */

enum rsac_error_t rsac_composition_builder_build(struct RsacCompositionBuilder *builder,
                                                 struct RsacComposition **out)
;
#endif

#if defined(RSAC_FEATURE_COMPOSE)
/**
 * Builds and starts one capture per source, resolves the composed channel
 * layout, and spawns the compositor thread.
 *
 * On failure every already-started inner capture is stopped before the error
 * is returned. Starting an already-started composition returns
 * `RSAC_ERROR_CONFIGURATION`.
 */
 enum rsac_error_t rsac_composition_start(struct RsacComposition *comp) ;
#endif

#if defined(RSAC_FEATURE_COMPOSE)
/**
 * Signals the composition to stop: ends the composed ring and tells the
 * compositor engine to stop every inner capture. Idempotent; a not-started
 * composition returns `RSAC_OK`.
 *
 * Takes a **const** composition: like `rsac_capture_request_stop()`, this is
 * safe to call concurrently with an in-flight [`rsac_composition_read`] /
 * [`rsac_composition_try_read`] to unblock it (no `&mut` alias is formed).
 * The compositor thread itself is joined later, by
 * [`rsac_composition_free`]. It is **NOT** safe to call this concurrently
 * with `rsac_composition_free()` — order stop + a drain of in-flight reads
 * **before** freeing the handle.
 *
 * An explicit stop discards any buffered composed tail: subsequent reads
 * return the terminal stream error rather than draining. To capture
 * everything, read until the terminal error *before* stopping.
 */
 enum rsac_error_t rsac_composition_stop(const struct RsacComposition *comp) ;
#endif

#if defined(RSAC_FEATURE_COMPOSE)
/**
 * Returns 1 if the composed stream is currently running, 0 otherwise.
 * Returns -1 if the composition handle is null.
 */
 int32_t rsac_composition_is_running(const struct RsacComposition *comp) ;
#endif

#if defined(RSAC_FEATURE_COMPOSE)
/**
 * Frees a composition handle. Stops the composition if running (joining the
 * compositor thread, which stops every inner capture). No-op if null.
 *
 * The composition owns its inner captures; freeing it releases them all.
 * `RsacAudioBuffer` handles previously returned by reads own their sample
 * data and remain valid after this call.
 */
 void rsac_composition_free(struct RsacComposition *comp) ;
#endif

#if defined(RSAC_FEATURE_COMPOSE)
/**
 * Attempts a non-blocking read of the next composed buffer (mirrors
 * `rsac_capture_try_read()`).
 *
 * On success with data available, `*out` receives a buffer handle that must
 * be freed with `rsac_audio_buffer_free()`; the data is interleaved f32 at
 * the session rate with [`rsac_composition_channel_count`] channels. On
 * success with no data available yet, `*out` is set to null and `RSAC_OK` is
 * returned. Once the composition has ended and drained, the read returns the
 * fatal `RSAC_ERROR_STREAM_FAILED` (terminal — do not retry). A composition
 * that has not been started returns `RSAC_ERROR_STREAM_READ`.
 */

enum rsac_error_t rsac_composition_try_read(const struct RsacComposition *comp,
                                            struct RsacAudioBuffer **out)
;
#endif

#if defined(RSAC_FEATURE_COMPOSE)
/**
 * Reads the next composed buffer, blocking until data is available (mirrors
 * `rsac_capture_read()`).
 *
 * On success, `*out` receives a buffer handle that must be freed with
 * `rsac_audio_buffer_free()`. Once the composition ends and drains, this
 * returns the fatal `RSAC_ERROR_STREAM_FAILED`. A concurrent
 * [`rsac_composition_stop`] unblocks a thread parked here.
 */

enum rsac_error_t rsac_composition_read(const struct RsacComposition *comp,
                                        struct RsacAudioBuffer **out)
;
#endif

#if defined(RSAC_FEATURE_COMPOSE)
/**
 * Returns the number of composed output channels.
 *
 * The layout is resolved by [`rsac_composition_start`] (keep-channels widths
 * depend on the source's negotiated format), so this returns 0 before a
 * successful start — and also 0 if the handle is null.
 */
 uint16_t rsac_composition_channel_count(const struct RsacComposition *comp) ;
#endif

#if defined(RSAC_FEATURE_COMPOSE)
/**
 * Returns the name of the group that produces composed output channel
 * `channel` (0-based).
 *
 * The returned pointer is valid until the next compose string accessor call
 * ([`rsac_composition_channel_group`], [`rsac_composition_source_group`], or
 * [`rsac_composition_source_target`]) on the same thread. Returns null if the
 * handle is null, the composition has not been started, or `channel` is out
 * of bounds.
 */
 const char *rsac_composition_channel_group(const struct RsacComposition *comp, uintptr_t channel) ;
#endif

#if defined(RSAC_FEATURE_COMPOSE)
/**
 * Returns the index of composed output channel `channel` *within* its group
 * (0-based; e.g. 0 = L, 1 = R for a stereo group).
 *
 * Returns -1 if the handle is null, the composition has not been started, or
 * `channel` is out of bounds.
 */
 int32_t rsac_composition_channel_in_group(const struct RsacComposition *comp, uintptr_t channel) ;
#endif

#if defined(RSAC_FEATURE_COMPOSE)
/**
 * Fills `*out` with a point-in-time [`RsacCompositionStats`] snapshot.
 *
 * Before [`rsac_composition_start`] succeeds the snapshot is all-zero
 * (`num_sources == 0`) — the compositor engine does not exist yet. `out` is
 * an out-parameter, not a handle: there is nothing to free.
 *
 * Returns `RSAC_ERROR_NULL_POINTER` if `comp` or `out` is null; otherwise
 * `RSAC_OK`.
 */

enum rsac_error_t rsac_composition_stats(const struct RsacComposition *comp,
                                         struct RsacCompositionStats *out)
;
#endif

#if defined(RSAC_FEATURE_COMPOSE)
/**
 * Fills `*out` with the [`RsacSourceStats`] counters of the source at
 * `index` (flat declaration order across all groups; valid indices are
 * `0..num_sources` from [`rsac_composition_stats`]).
 *
 * Returns `RSAC_ERROR_NULL_POINTER` if `comp` or `out` is null,
 * `RSAC_ERROR_STREAM_READ` if the composition has not been started (per-source
 * counters exist only while the engine does), and
 * `RSAC_ERROR_INVALID_PARAMETER` if `index` is out of bounds. `out` is an
 * out-parameter, not a handle: there is nothing to free.
 */

enum rsac_error_t rsac_composition_source_stats(const struct RsacComposition *comp,
                                                uintptr_t index,
                                                struct RsacSourceStats *out)
;
#endif

#if defined(RSAC_FEATURE_COMPOSE)
/**
 * Returns the group name of the source at `index` (flat declaration order).
 *
 * The returned pointer is valid until the next compose string accessor call
 * on the same thread. Returns null if the handle is null, the composition has
 * not been started, or `index` is out of bounds.
 */
 const char *rsac_composition_source_group(const struct RsacComposition *comp, uintptr_t index) ;
#endif

#if defined(RSAC_FEATURE_COMPOSE)
/**
 * Returns the capture-target string of the source at `index` (flat
 * declaration order), rendered in the canonical `CaptureTarget` grammar
 * (e.g. `"system"`, `"name:discord"`).
 *
 * The returned pointer is valid until the next compose string accessor call
 * on the same thread. Returns null if the handle is null, the composition has
 * not been started, or `index` is out of bounds.
 */
 const char *rsac_composition_source_target(const struct RsacComposition *comp, uintptr_t index) ;
#endif

#endif  /* RSAC_H */
