#ifndef RSAC_H
#define RSAC_H

/* Warning: this file is autogenerated by cbindgen. Do not modify manually. */

#include <stdarg.h>
#include <stdbool.h>
#include <stdint.h>
#include <stdlib.h>

/**
 * Device kind for enumeration.
 */
typedef enum rsac_device_kind_t {
    RSAC_DEVICE_INPUT = 0,
    RSAC_DEVICE_OUTPUT = 1,
} rsac_device_kind_t;

/**
 * Error codes returned by all rsac FFI functions.
 */
typedef enum rsac_error_t {
    /**
     * Operation succeeded.
     */
    RSAC_OK = 0,
    /**
     * A null pointer was passed where a valid pointer was expected.
     */
    RSAC_ERROR_NULL_POINTER = 1,
    /**
     * Invalid parameter value.
     */
    RSAC_ERROR_INVALID_PARAMETER = 2,
    /**
     * The requested device was not found.
     */
    RSAC_ERROR_DEVICE_NOT_FOUND = 3,
    /**
     * The requested feature is not supported on this platform.
     */
    RSAC_ERROR_PLATFORM_NOT_SUPPORTED = 4,
    /**
     * Failed to create or start an audio stream.
     */
    RSAC_ERROR_STREAM_FAILED = 5,
    /**
     * Failed to read audio data from the stream.
     */
    RSAC_ERROR_STREAM_READ = 6,
    /**
     * A configuration error occurred.
     */
    RSAC_ERROR_CONFIGURATION = 7,
    /**
     * The target application was not found.
     */
    RSAC_ERROR_APPLICATION_NOT_FOUND = 8,
    /**
     * A backend-specific error occurred.
     */
    RSAC_ERROR_BACKEND = 9,
    /**
     * Permission denied.
     */
    RSAC_ERROR_PERMISSION_DENIED = 10,
    /**
     * An operation timed out.
     */
    RSAC_ERROR_TIMEOUT = 11,
    /**
     * An internal or unknown error occurred.
     */
    RSAC_ERROR_INTERNAL = 12,
    /**
     * A Rust panic was caught (should not happen in normal use).
     */
    RSAC_ERROR_PANIC = 99,
} rsac_error_t;

/**
 * Sample wire/storage format, mirroring [`rsac::SampleFormat`].
 *
 * All audio data is delivered as interleaved `f32` regardless of this value;
 * it describes the negotiated wire format the backend reports.
 */
typedef enum rsac_sample_format_t {
    /**
     * Signed 16-bit integer.
     */
    RSAC_SAMPLE_FORMAT_I16 = 0,
    /**
     * Signed 24-bit integer (packed in a 32-bit container).
     */
    RSAC_SAMPLE_FORMAT_I24 = 1,
    /**
     * Signed 32-bit integer.
     */
    RSAC_SAMPLE_FORMAT_I32 = 2,
    /**
     * 32-bit IEEE 754 floating-point (the library's internal standard).
     */
    RSAC_SAMPLE_FORMAT_F32 = 3,
} rsac_sample_format_t;

/**
 * Opaque handle to an `AudioBuffer`.
 */
typedef struct RsacAudioBuffer RsacAudioBuffer;

/**
 * Opaque handle to an `AudioCaptureBuilder`.
 */
typedef struct RsacBuilder RsacBuilder;

/**
 * Opaque handle to platform capabilities.
 */
typedef struct RsacCapabilities RsacCapabilities;

/**
 * Opaque handle to an `AudioCapture` session.
 */
typedef struct RsacCapture RsacCapture;

/**
 * Opaque handle to a single audio device.
 */
typedef struct RsacDevice RsacDevice;

/**
 * Opaque handle to a device enumerator.
 */
typedef struct RsacDeviceEnumerator RsacDeviceEnumerator;

/**
 * Opaque handle to a list of audio devices.
 */
typedef struct RsacDeviceList RsacDeviceList;

/**
 * A point-in-time snapshot of a capture's stream statistics.
 *
 * Filled by [`rsac_capture_stream_stats`] from [`AudioCapture::stream_stats`].
 * This is a plain C-ABI value type (no heap, no free required). It mirrors the
 * counters in [`rsac::StreamStats`]; `is_running` is `1` when capturing, else `0`.
 *
 * When no stream has been created (before start, or after stop) every counter
 * is `0`, `uptime_secs` is `0.0`, and `is_running` is `0`.
 */
typedef struct RsacStreamStats {
    /**
     * Buffers delivered to the consumer (popped off the ring) since start.
     */
    uint64_t buffers_captured;
    /**
     * Buffers dropped due to ring-buffer overflow since start.
     */
    uint64_t buffers_dropped;
    /**
     * Buffers enqueued by the producer (the OS audio callback) since start.
     */
    uint64_t buffers_pushed;
    /**
     * Ring-buffer overruns. Equal to `buffers_dropped` (retained alias).
     */
    uint64_t overruns;
    /**
     * How long the stream has been running, in seconds. `0.0` when not started.
     */
    double uptime_secs;
    /**
     * Fraction of accounted-for buffers lost to overflow, in `0.0..=1.0`.
     */
    double dropped_ratio;
    /**
     * `1` if the stream is currently capturing, `0` otherwise.
     */
    int32_t is_running;
} RsacStreamStats;

/**
 * A point-in-time snapshot of a capture's negotiated delivery format.
 *
 * Filled by [`rsac_capture_format`] from [`AudioCapture::format`]. Plain C-ABI
 * value type (no heap, no free required).
 */
typedef struct RsacAudioFormat {
    /**
     * Samples per second (e.g. 44100, 48000).
     */
    uint32_t sample_rate;
    /**
     * Number of audio channels (e.g. 1 mono, 2 stereo).
     */
    uint16_t channels;
    /**
     * The negotiated sample wire format.
     */
    enum rsac_sample_format_t sample_format;
    /**
     * Bits per sample for `sample_format` (16, 24, or 32).
     */
    uint16_t bits_per_sample;
} RsacAudioFormat;

/**
 * C callback type for audio data.
 *
 * Called with:
 * - `buffer_data`: pointer to interleaved f32 sample data
 * - `num_samples`: total number of f32 values in buffer_data
 * - `channels`: number of audio channels
 * - `sample_rate`: sample rate in Hz
 * - `user_data`: opaque pointer passed to `rsac_capture_set_callback`
 */
typedef void (*rsac_audio_callback_t)(const float *buffer_data,
                                      uintptr_t num_samples,
                                      uint16_t channels,
                                      uint32_t sample_rate,
                                      void *user_data);

/**
 * Returns a pointer to the last error message for the current thread.
 *
 * The returned string is valid until the next rsac FFI call on this thread.
 * Returns an empty string if no error has occurred.
 */
 const char *rsac_error_message(void) ;

/**
 * Creates a new `AudioCaptureBuilder` with default settings.
 *
 * Returns a handle that must be freed with `rsac_builder_free()`.
 * On failure, `*out` is set to null.
 */
 enum rsac_error_t rsac_builder_new(struct RsacBuilder **out) ;

/**
 * Frees a builder handle. No-op if null.
 */
 void rsac_builder_free(struct RsacBuilder *builder) ;

/**
 * Sets the capture target to system default audio.
 */
 enum rsac_error_t rsac_builder_set_target_system(struct RsacBuilder *builder) ;

/**
 * Sets the capture target to a specific device by ID.
 */

enum rsac_error_t rsac_builder_set_target_device(struct RsacBuilder *builder,
                                                 const char *device_id)
;

/**
 * Sets the capture target to an application by name.
 */

enum rsac_error_t rsac_builder_set_target_app_by_name(struct RsacBuilder *builder,
                                                      const char *app_name)
;

/**
 * Sets the capture target to an application by ID.
 */

enum rsac_error_t rsac_builder_set_target_app_by_id(struct RsacBuilder *builder,
                                                    const char *app_id)
;

/**
 * Sets the capture target to a process tree by PID.
 */
 enum rsac_error_t rsac_builder_set_target_process_tree(struct RsacBuilder *builder, uint32_t pid) ;

/**
 * Sets the capture target by parsing a canonical target string.
 *
 * `spec` uses the [`CaptureTarget`] string grammar (case-insensitive scheme):
 * `system`, `device:<id>`, `app:<pid-or-id>`, `name:<name>`, or `tree:<pid>`.
 * Parsing goes through `CaptureTarget::from_str` (the same path
 * [`AudioCaptureBuilder::target_str`] uses), so it round-trips with
 * [`rsac::CaptureTarget`]'s `Display`.
 *
 * A malformed string is reported as `RSAC_ERROR_INVALID_PARAMETER` and the
 * builder's existing target is left unchanged (parse-then-commit). This is a
 * convenience over the typed `rsac_builder_set_target_*` setters, which remain
 * available.
 *
 * Returns `RSAC_ERROR_NULL_POINTER` if `builder` or `spec` is null, and
 * `RSAC_ERROR_INVALID_PARAMETER` if `spec` is not valid UTF-8 or not a valid
 * target string.
 */
 enum rsac_error_t rsac_builder_set_target_str(struct RsacBuilder *builder, const char *spec) ;

/**
 * Sets the desired sample rate in Hz.
 */
 enum rsac_error_t rsac_builder_set_sample_rate(struct RsacBuilder *builder, uint32_t sample_rate) ;

/**
 * Sets the desired number of audio channels.
 */
 enum rsac_error_t rsac_builder_set_channels(struct RsacBuilder *builder, uint16_t channels) ;

/**
 * Builds an `AudioCapture` from the builder configuration.
 *
 * On success, `*out` receives the capture handle. The builder is consumed
 * and freed. On failure, `*out` is null and the builder is also consumed
 * (Rust ownership semantics — create a new builder to retry).
 */
 enum rsac_error_t rsac_builder_build(struct RsacBuilder *builder, struct RsacCapture **out) ;

/**
 * Starts the audio capture stream.
 */
 enum rsac_error_t rsac_capture_start(struct RsacCapture *capture) ;

/**
 * Stops the audio capture stream.
 */
 enum rsac_error_t rsac_capture_stop(struct RsacCapture *capture) ;

/**
 * Returns 1 if the capture stream is currently running, 0 otherwise.
 * Returns -1 if the capture handle is null.
 */
 int32_t rsac_capture_is_running(const struct RsacCapture *capture) ;

/**
 * Returns the number of ring buffer overruns (dropped buffers).
 * Returns 0 if the capture handle is null or no stream exists.
 */
 uint64_t rsac_capture_overrun_count(const struct RsacCapture *capture) ;

/**
 * Fills `*out` with a point-in-time [`RsacStreamStats`] snapshot of the capture.
 *
 * The snapshot bundles the bridge's diagnostic counters with the running state,
 * uptime, and overflow ratio. Reading it never allocates on or blocks the OS
 * audio callback thread.
 *
 * When no stream has been created (before start, or after stop), `*out` is
 * filled with an all-zero snapshot (`is_running == 0`).
 *
 * Returns `RSAC_ERROR_NULL_POINTER` if `capture` or `out` is null; otherwise
 * `RSAC_OK`. `out` is an out-parameter, not a handle: there is nothing to free.
 */

enum rsac_error_t rsac_capture_stream_stats(const struct RsacCapture *capture,
                                            struct RsacStreamStats *out)
;

/**
 * Fills `*out` with the negotiated delivery [`RsacAudioFormat`] of the capture.
 *
 * This is the format the backend actually produces, atomically published by the
 * bridge once a stream is created. Returns `RSAC_ERROR_STREAM_FAILED` when no
 * stream has been created yet (before start, or after stop), leaving `*out`
 * untouched — call this only on a started capture, or after checking
 * [`rsac_capture_is_running`].
 *
 * Returns `RSAC_ERROR_NULL_POINTER` if `capture` or `out` is null. `out` is an
 * out-parameter, not a handle: there is nothing to free.
 */

enum rsac_error_t rsac_capture_format(const struct RsacCapture *capture,
                                      struct RsacAudioFormat *out)
;

/**
 * Frees a capture handle. Stops the stream if running. No-op if null.
 */
 void rsac_capture_free(struct RsacCapture *capture) ;

/**
 * Attempts a non-blocking read of audio data.
 *
 * On success with data available, `*out` receives a buffer handle.
 * On success with no data available, `*out` is set to null and RSAC_OK is returned.
 * The buffer must be freed with `rsac_audio_buffer_free()`.
 */

enum rsac_error_t rsac_capture_try_read(const struct RsacCapture *capture,
                                        struct RsacAudioBuffer **out)
;

/**
 * Reads audio data, blocking until data is available.
 *
 * On success, `*out` receives a buffer handle that must be freed
 * with `rsac_audio_buffer_free()`.
 */

enum rsac_error_t rsac_capture_read(const struct RsacCapture *capture,
                                    struct RsacAudioBuffer **out)
;

/**
 * Best-effort request to stop the capture, used to **unblock a parked
 * [`rsac_capture_read`]**.
 *
 * Transitions the underlying stream toward its terminal state so a thread
 * blocked in `rsac_capture_read` returns promptly (with a terminal stream
 * error) instead of waiting out the blocking-read timeout. It is idempotent
 * and a no-op when no stream has been created (or it is already stopped).
 *
 * # Safety / ordering
 *
 * - Takes `*const RsacCapture`: it is **safe to call concurrently with an
 *   in-flight `rsac_capture_read` / `rsac_capture_try_read`** to unblock it
 *   (it forms no `&mut` alias to the capture).
 * - It is **NOT** safe to call concurrently with `rsac_capture_free`. The
 *   caller must order `request_stop` + a drain of in-flight reads **before**
 *   freeing the handle (the sqlite3_interrupt contract).
 *
 * Returns `RSAC_ERROR_NULL_POINTER` if `capture` is null, else `RSAC_OK`.
 */
 enum rsac_error_t rsac_capture_request_stop(const struct RsacCapture *capture) ;

/**
 * Sets a callback for push-based audio delivery.
 *
 * The callback is invoked on a background thread for each captured audio buffer.
 * Must be called before `rsac_capture_start()`.
 *
 * Pass `callback = NULL` to clear the callback.
 *
 * # Safety
 *
 * - `user_data` is passed through to the callback unchanged; the caller is
 *   responsible for its lifetime and thread safety.
 * - The callback must not call any rsac functions (to avoid deadlocks).
 */

enum rsac_error_t rsac_capture_set_callback(struct RsacCapture *capture,
                                            rsac_audio_callback_t callback,
                                            void *user_data)
;

/**
 * Returns a pointer to the interleaved f32 sample data.
 *
 * The pointer is valid until the buffer is freed. Returns null if the buffer is null.
 */
 const float *rsac_audio_buffer_data(const struct RsacAudioBuffer *buffer) ;

/**
 * Returns the total number of f32 samples in the buffer (all channels).
 * Returns 0 if the buffer is null.
 */
 uintptr_t rsac_audio_buffer_len(const struct RsacAudioBuffer *buffer) ;

/**
 * Returns the number of audio frames in the buffer.
 * Returns 0 if the buffer is null.
 */
 uintptr_t rsac_audio_buffer_num_frames(const struct RsacAudioBuffer *buffer) ;

/**
 * Returns the number of channels in the buffer.
 * Returns 0 if the buffer is null.
 */
 uint16_t rsac_audio_buffer_channels(const struct RsacAudioBuffer *buffer) ;

/**
 * Returns the sample rate of the buffer in Hz.
 * Returns 0 if the buffer is null.
 */
 uint32_t rsac_audio_buffer_sample_rate(const struct RsacAudioBuffer *buffer) ;

/**
 * Returns the root-mean-square (RMS) level across all samples/channels.
 *
 * Wraps [`rsac::AudioBuffer::rms`]: `sqrt(mean(xᵢ²))` over the interleaved
 * data. Non-finite samples are skipped; a silent or empty buffer yields `0.0`
 * (never `NaN`). Read-only measurement — no allocation, RT-callback safe.
 * Returns `0.0` if the buffer is null.
 */
 float rsac_audio_buffer_rms(const struct RsacAudioBuffer *buffer) ;

/**
 * Returns the peak (maximum absolute) level across all samples/channels.
 *
 * Wraps [`rsac::AudioBuffer::peak`]: `max(|xᵢ|)`. Non-finite samples are
 * skipped; a silent or empty buffer yields `0.0` (never `NaN`). Read-only
 * measurement — no allocation. Returns `0.0` if the buffer is null.
 */
 float rsac_audio_buffer_peak(const struct RsacAudioBuffer *buffer) ;

/**
 * Returns the RMS level in dBFS: `20 · log10(rms())`.
 *
 * Wraps [`rsac::AudioBuffer::rms_dbfs`]. Returns negative infinity for silence
 * or an empty buffer, and **also** negative infinity if the buffer is null
 * (there is no level to report). Full scale (RMS `1.0`) maps to `0.0` dBFS.
 */
 float rsac_audio_buffer_rms_dbfs(const struct RsacAudioBuffer *buffer) ;

/**
 * Returns the peak level in dBFS: `20 · log10(peak())`.
 *
 * Wraps [`rsac::AudioBuffer::peak_dbfs`]. Returns negative infinity for silence
 * or an empty buffer, and **also** negative infinity if the buffer is null.
 * A full-scale signal (peak `1.0`) maps to `0.0` dBFS.
 */
 float rsac_audio_buffer_peak_dbfs(const struct RsacAudioBuffer *buffer) ;

/**
 * Frees an audio buffer handle. No-op if null.
 */
 void rsac_audio_buffer_free(struct RsacAudioBuffer *buffer) ;

/**
 * Creates a new device enumerator.
 *
 * On success, `*out` receives the enumerator handle. Must be freed with
 * `rsac_device_enumerator_free()`.
 */
 enum rsac_error_t rsac_device_enumerator_new(struct RsacDeviceEnumerator **out) ;

/**
 * Frees a device enumerator handle. No-op if null.
 */
 void rsac_device_enumerator_free(struct RsacDeviceEnumerator *enumerator) ;

/**
 * Enumerates all audio devices into a device list.
 *
 * On success, `*out` receives the device list handle. Must be freed with
 * `rsac_device_list_free()`.
 */

enum rsac_error_t rsac_device_list_new(const struct RsacDeviceEnumerator *enumerator,
                                       struct RsacDeviceList **out)
;

/**
 * Returns the number of devices in the list.
 * Returns 0 if the list is null.
 */
 uintptr_t rsac_device_list_count(const struct RsacDeviceList *list) ;

/**
 * Gets a device from the list by index.
 *
 * On success, `*out` receives a device handle that must be freed with
 * `rsac_device_free()`. Returns an error if the index is out of bounds.
 *
 * The returned device is a snapshot — it carries the device's name, ID,
 * and default status, but cannot be used to create streams directly.
 */

enum rsac_error_t rsac_device_list_get(const struct RsacDeviceList *list,
                                       uintptr_t index,
                                       struct RsacDevice **out)
;

/**
 * Frees a device list handle. No-op if null.
 */
 void rsac_device_list_free(struct RsacDeviceList *list) ;

/**
 * Gets the default audio device.
 *
 * On success, `*out` receives a device handle that must be freed with
 * `rsac_device_free()`.
 */

enum rsac_error_t rsac_default_device(const struct RsacDeviceEnumerator *enumerator,
                                      enum rsac_device_kind_t kind,
                                      struct RsacDevice **out)
;

/**
 * Returns the device name as a C string.
 *
 * The returned pointer is valid until the next call to `rsac_device_name()` or
 * `rsac_device_id()` on the same thread. Returns null if the device handle is null.
 */
 const char *rsac_device_name(const struct RsacDevice *device) ;

/**
 * Returns the device ID as a C string.
 *
 * The returned pointer is valid until the next call to `rsac_device_name()` or
 * `rsac_device_id()` on the same thread. Returns null if the device handle is null.
 */
 const char *rsac_device_id(const struct RsacDevice *device) ;

/**
 * Returns 1 if the device is the system default, 0 otherwise.
 * Returns -1 if the device handle is null.
 */
 int32_t rsac_device_is_default(const struct RsacDevice *device) ;

/**
 * Frees a device handle. No-op if null.
 */
 void rsac_device_free(struct RsacDevice *device) ;

/**
 * Queries platform capabilities.
 *
 * On success, `*out` receives a capabilities handle. Must be freed with
 * `rsac_capabilities_free()`.
 */
 enum rsac_error_t rsac_capabilities_query(struct RsacCapabilities **out) ;

/**
 * Frees a capabilities handle. No-op if null.
 */
 void rsac_capabilities_free(struct RsacCapabilities *caps) ;

/**
 * Returns 1 if system capture is supported, 0 otherwise.
 * Returns -1 if the handle is null.
 */
 int32_t rsac_capabilities_supports_system_capture(const struct RsacCapabilities *caps) ;

/**
 * Returns 1 if application capture is supported, 0 otherwise.
 * Returns -1 if the handle is null.
 */
 int32_t rsac_capabilities_supports_app_capture(const struct RsacCapabilities *caps) ;

/**
 * Returns 1 if process tree capture is supported, 0 otherwise.
 * Returns -1 if the handle is null.
 */
 int32_t rsac_capabilities_supports_process_tree(const struct RsacCapabilities *caps) ;

/**
 * Returns 1 if device selection is supported, 0 otherwise.
 * Returns -1 if the handle is null.
 */
 int32_t rsac_capabilities_supports_device_selection(const struct RsacCapabilities *caps) ;

/**
 * Returns the maximum number of channels supported.
 * Returns 0 if the handle is null.
 */
 uint16_t rsac_capabilities_max_channels(const struct RsacCapabilities *caps) ;

/**
 * Returns the backend name (e.g., "WASAPI", "CoreAudio", "PipeWire") as a C string.
 *
 * The returned pointer is valid until the next call to `rsac_capabilities_backend_name()`
 * on the same thread. Returns null if the handle is null.
 */
 const char *rsac_capabilities_backend_name(const struct RsacCapabilities *caps) ;

/**
 * Returns the rsac-ffi version string.
 *
 * The returned pointer is a static string valid for the lifetime of the library.
 */
 const char *rsac_version(void) ;

#endif  /* RSAC_H */
