#ifndef RSAC_H
#define RSAC_H

/* Warning: this file is autogenerated by cbindgen. Do not modify manually. */

#include <stdarg.h>
#include <stdbool.h>
#include <stdint.h>
#include <stdlib.h>

/**
 * Device kind for enumeration.
 */
typedef enum Rsacrsac_device_kind_t {
    RSAC_DEVICE_INPUT = 0,
    RSAC_DEVICE_OUTPUT = 1,
} Rsacrsac_device_kind_t;

/**
 * Error codes returned by all rsac FFI functions.
 */
typedef enum Rsacrsac_error_t {
    /**
     * Operation succeeded.
     */
    RSAC_OK = 0,
    /**
     * A null pointer was passed where a valid pointer was expected.
     */
    RSAC_ERROR_NULL_POINTER = 1,
    /**
     * Invalid parameter value.
     */
    RSAC_ERROR_INVALID_PARAMETER = 2,
    /**
     * The requested device was not found.
     */
    RSAC_ERROR_DEVICE_NOT_FOUND = 3,
    /**
     * The requested feature is not supported on this platform.
     */
    RSAC_ERROR_PLATFORM_NOT_SUPPORTED = 4,
    /**
     * Failed to create or start an audio stream.
     */
    RSAC_ERROR_STREAM_FAILED = 5,
    /**
     * Failed to read audio data from the stream.
     */
    RSAC_ERROR_STREAM_READ = 6,
    /**
     * A configuration error occurred.
     */
    RSAC_ERROR_CONFIGURATION = 7,
    /**
     * The target application was not found.
     */
    RSAC_ERROR_APPLICATION_NOT_FOUND = 8,
    /**
     * A backend-specific error occurred.
     */
    RSAC_ERROR_BACKEND = 9,
    /**
     * Permission denied.
     */
    RSAC_ERROR_PERMISSION_DENIED = 10,
    /**
     * An operation timed out.
     */
    RSAC_ERROR_TIMEOUT = 11,
    /**
     * An internal or unknown error occurred.
     */
    RSAC_ERROR_INTERNAL = 12,
    /**
     * A Rust panic was caught (should not happen in normal use).
     */
    RSAC_ERROR_PANIC = 99,
} Rsacrsac_error_t;

/**
 * Opaque handle to an `AudioBuffer`.
 */
typedef struct RsacRsacAudioBuffer RsacRsacAudioBuffer;

/**
 * Opaque handle to an `AudioCaptureBuilder`.
 */
typedef struct RsacRsacBuilder RsacRsacBuilder;

/**
 * Opaque handle to platform capabilities.
 */
typedef struct RsacRsacCapabilities RsacRsacCapabilities;

/**
 * Opaque handle to an `AudioCapture` session.
 */
typedef struct RsacRsacCapture RsacRsacCapture;

/**
 * Opaque handle to a single audio device.
 */
typedef struct RsacRsacDevice RsacRsacDevice;

/**
 * Opaque handle to a device enumerator.
 */
typedef struct RsacRsacDeviceEnumerator RsacRsacDeviceEnumerator;

/**
 * Opaque handle to a list of audio devices.
 */
typedef struct RsacRsacDeviceList RsacRsacDeviceList;

/**
 * C callback type for audio data.
 *
 * Called with:
 * - `buffer_data`: pointer to interleaved f32 sample data
 * - `num_samples`: total number of f32 values in buffer_data
 * - `channels`: number of audio channels
 * - `sample_rate`: sample rate in Hz
 * - `user_data`: opaque pointer passed to `rsac_capture_set_callback`
 */
typedef void (*Rsacrsac_audio_callback_t)(const float *buffer_data,
                                          uintptr_t num_samples,
                                          uint16_t channels,
                                          uint32_t sample_rate,
                                          void *user_data);

/**
 * Returns a pointer to the last error message for the current thread.
 *
 * The returned string is valid until the next rsac FFI call on this thread.
 * Returns an empty string if no error has occurred.
 */
 const char *rsac_error_message(void) ;

/**
 * Creates a new `AudioCaptureBuilder` with default settings.
 *
 * Returns a handle that must be freed with `rsac_builder_free()`.
 * On failure, `*out` is set to null.
 */
 enum Rsacrsac_error_t rsac_builder_new(struct RsacRsacBuilder **out) ;

/**
 * Frees a builder handle. No-op if null.
 */
 void rsac_builder_free(struct RsacRsacBuilder *builder) ;

/**
 * Sets the capture target to system default audio.
 */
 enum Rsacrsac_error_t rsac_builder_set_target_system(struct RsacRsacBuilder *builder) ;

/**
 * Sets the capture target to a specific device by ID.
 */

enum Rsacrsac_error_t rsac_builder_set_target_device(struct RsacRsacBuilder *builder,
                                                     const char *device_id)
;

/**
 * Sets the capture target to an application by name.
 */

enum Rsacrsac_error_t rsac_builder_set_target_app_by_name(struct RsacRsacBuilder *builder,
                                                          const char *app_name)
;

/**
 * Sets the capture target to an application by ID.
 */

enum Rsacrsac_error_t rsac_builder_set_target_app_by_id(struct RsacRsacBuilder *builder,
                                                        const char *app_id)
;

/**
 * Sets the capture target to a process tree by PID.
 */

enum Rsacrsac_error_t rsac_builder_set_target_process_tree(struct RsacRsacBuilder *builder,
                                                           uint32_t pid)
;

/**
 * Sets the desired sample rate in Hz.
 */

enum Rsacrsac_error_t rsac_builder_set_sample_rate(struct RsacRsacBuilder *builder,
                                                   uint32_t sample_rate)
;

/**
 * Sets the desired number of audio channels.
 */

enum Rsacrsac_error_t rsac_builder_set_channels(struct RsacRsacBuilder *builder,
                                                uint16_t channels)
;

/**
 * Builds an `AudioCapture` from the builder configuration.
 *
 * On success, `*out` receives the capture handle. The builder is consumed
 * and freed. On failure, `*out` is null and the builder is also consumed
 * (Rust ownership semantics — create a new builder to retry).
 */

enum Rsacrsac_error_t rsac_builder_build(struct RsacRsacBuilder *builder,
                                         struct RsacRsacCapture **out)
;

/**
 * Starts the audio capture stream.
 */
 enum Rsacrsac_error_t rsac_capture_start(struct RsacRsacCapture *capture) ;

/**
 * Stops the audio capture stream.
 */
 enum Rsacrsac_error_t rsac_capture_stop(struct RsacRsacCapture *capture) ;

/**
 * Returns 1 if the capture stream is currently running, 0 otherwise.
 * Returns -1 if the capture handle is null.
 */
 int32_t rsac_capture_is_running(const struct RsacRsacCapture *capture) ;

/**
 * Returns the number of ring buffer overruns (dropped buffers).
 * Returns 0 if the capture handle is null or no stream exists.
 */
 uint64_t rsac_capture_overrun_count(const struct RsacRsacCapture *capture) ;

/**
 * Frees a capture handle. Stops the stream if running. No-op if null.
 */
 void rsac_capture_free(struct RsacRsacCapture *capture) ;

/**
 * Attempts a non-blocking read of audio data.
 *
 * On success with data available, `*out` receives a buffer handle.
 * On success with no data available, `*out` is set to null and RSAC_OK is returned.
 * The buffer must be freed with `rsac_audio_buffer_free()`.
 */

enum Rsacrsac_error_t rsac_capture_try_read(struct RsacRsacCapture *capture,
                                            struct RsacRsacAudioBuffer **out)
;

/**
 * Reads audio data, blocking until data is available.
 *
 * On success, `*out` receives a buffer handle that must be freed
 * with `rsac_audio_buffer_free()`.
 */

enum Rsacrsac_error_t rsac_capture_read(struct RsacRsacCapture *capture,
                                        struct RsacRsacAudioBuffer **out)
;

/**
 * Sets a callback for push-based audio delivery.
 *
 * The callback is invoked on a background thread for each captured audio buffer.
 * Must be called before `rsac_capture_start()`.
 *
 * Pass `callback = NULL` to clear the callback.
 *
 * # Safety
 *
 * - `user_data` is passed through to the callback unchanged; the caller is
 *   responsible for its lifetime and thread safety.
 * - The callback must not call any rsac functions (to avoid deadlocks).
 */

enum Rsacrsac_error_t rsac_capture_set_callback(struct RsacRsacCapture *capture,
                                                Rsacrsac_audio_callback_t callback,
                                                void *user_data)
;

/**
 * Returns a pointer to the interleaved f32 sample data.
 *
 * The pointer is valid until the buffer is freed. Returns null if the buffer is null.
 */
 const float *rsac_audio_buffer_data(const struct RsacRsacAudioBuffer *buffer) ;

/**
 * Returns the total number of f32 samples in the buffer (all channels).
 * Returns 0 if the buffer is null.
 */
 uintptr_t rsac_audio_buffer_len(const struct RsacRsacAudioBuffer *buffer) ;

/**
 * Returns the number of audio frames in the buffer.
 * Returns 0 if the buffer is null.
 */
 uintptr_t rsac_audio_buffer_num_frames(const struct RsacRsacAudioBuffer *buffer) ;

/**
 * Returns the number of channels in the buffer.
 * Returns 0 if the buffer is null.
 */
 uint16_t rsac_audio_buffer_channels(const struct RsacRsacAudioBuffer *buffer) ;

/**
 * Returns the sample rate of the buffer in Hz.
 * Returns 0 if the buffer is null.
 */
 uint32_t rsac_audio_buffer_sample_rate(const struct RsacRsacAudioBuffer *buffer) ;

/**
 * Frees an audio buffer handle. No-op if null.
 */
 void rsac_audio_buffer_free(struct RsacRsacAudioBuffer *buffer) ;

/**
 * Creates a new device enumerator.
 *
 * On success, `*out` receives the enumerator handle. Must be freed with
 * `rsac_device_enumerator_free()`.
 */
 enum Rsacrsac_error_t rsac_device_enumerator_new(struct RsacRsacDeviceEnumerator **out) ;

/**
 * Frees a device enumerator handle. No-op if null.
 */
 void rsac_device_enumerator_free(struct RsacRsacDeviceEnumerator *enumerator) ;

/**
 * Enumerates all audio devices into a device list.
 *
 * On success, `*out` receives the device list handle. Must be freed with
 * `rsac_device_list_free()`.
 */

enum Rsacrsac_error_t rsac_device_list_new(const struct RsacRsacDeviceEnumerator *enumerator,
                                           struct RsacRsacDeviceList **out)
;

/**
 * Returns the number of devices in the list.
 * Returns 0 if the list is null.
 */
 uintptr_t rsac_device_list_count(const struct RsacRsacDeviceList *list) ;

/**
 * Gets a device from the list by index.
 *
 * On success, `*out` receives a device handle that must be freed with
 * `rsac_device_free()`. Returns an error if the index is out of bounds.
 *
 * The returned device is a snapshot — it carries the device's name, ID,
 * and default status, but cannot be used to create streams directly.
 */

enum Rsacrsac_error_t rsac_device_list_get(const struct RsacRsacDeviceList *list,
                                           uintptr_t index,
                                           struct RsacRsacDevice **out)
;

/**
 * Frees a device list handle. No-op if null.
 */
 void rsac_device_list_free(struct RsacRsacDeviceList *list) ;

/**
 * Gets the default audio device.
 *
 * On success, `*out` receives a device handle that must be freed with
 * `rsac_device_free()`.
 */

enum Rsacrsac_error_t rsac_default_device(const struct RsacRsacDeviceEnumerator *enumerator,
                                          enum Rsacrsac_device_kind_t kind,
                                          struct RsacRsacDevice **out)
;

/**
 * Returns the device name as a C string.
 *
 * The returned pointer is valid until the next call to `rsac_device_name()` or
 * `rsac_device_id()` on the same thread. Returns null if the device handle is null.
 */
 const char *rsac_device_name(const struct RsacRsacDevice *device) ;

/**
 * Returns the device ID as a C string.
 *
 * The returned pointer is valid until the next call to `rsac_device_name()` or
 * `rsac_device_id()` on the same thread. Returns null if the device handle is null.
 */
 const char *rsac_device_id(const struct RsacRsacDevice *device) ;

/**
 * Returns 1 if the device is the system default, 0 otherwise.
 * Returns -1 if the device handle is null.
 */
 int32_t rsac_device_is_default(const struct RsacRsacDevice *device) ;

/**
 * Frees a device handle. No-op if null.
 */
 void rsac_device_free(struct RsacRsacDevice *device) ;

/**
 * Queries platform capabilities.
 *
 * On success, `*out` receives a capabilities handle. Must be freed with
 * `rsac_capabilities_free()`.
 */
 enum Rsacrsac_error_t rsac_capabilities_query(struct RsacRsacCapabilities **out) ;

/**
 * Frees a capabilities handle. No-op if null.
 */
 void rsac_capabilities_free(struct RsacRsacCapabilities *caps) ;

/**
 * Returns 1 if system capture is supported, 0 otherwise.
 * Returns -1 if the handle is null.
 */
 int32_t rsac_capabilities_supports_system_capture(const struct RsacRsacCapabilities *caps) ;

/**
 * Returns 1 if application capture is supported, 0 otherwise.
 * Returns -1 if the handle is null.
 */
 int32_t rsac_capabilities_supports_app_capture(const struct RsacRsacCapabilities *caps) ;

/**
 * Returns 1 if process tree capture is supported, 0 otherwise.
 * Returns -1 if the handle is null.
 */
 int32_t rsac_capabilities_supports_process_tree(const struct RsacRsacCapabilities *caps) ;

/**
 * Returns 1 if device selection is supported, 0 otherwise.
 * Returns -1 if the handle is null.
 */
 int32_t rsac_capabilities_supports_device_selection(const struct RsacRsacCapabilities *caps) ;

/**
 * Returns the maximum number of channels supported.
 * Returns 0 if the handle is null.
 */
 uint16_t rsac_capabilities_max_channels(const struct RsacRsacCapabilities *caps) ;

/**
 * Returns the backend name (e.g., "WASAPI", "CoreAudio", "PipeWire") as a C string.
 *
 * The returned pointer is valid until the next call to `rsac_capabilities_backend_name()`
 * on the same thread. Returns null if the handle is null.
 */
 const char *rsac_capabilities_backend_name(const struct RsacRsacCapabilities *caps) ;

/**
 * Returns the rsac-ffi version string.
 *
 * The returned pointer is a static string valid for the lifetime of the library.
 */
 const char *rsac_version(void) ;

#endif  /* RSAC_H */
