default-sample-rate = 44100
default-fragments = 4
default-fragment-size-msec = 25
exit-idle-time = -1
load-module module-native-protocol-tcp auth-anonymous=1
load-module module-null-sink sink_name=test_sink 