#!/usr/bin/env bash
# scripts/hooks/commit-msg.sh — enforce the repo's commit-message rules
# (AGENTS.md §6, "Git commit conventions") mechanically via lefthook.
#
# Rejected:
#   - Co-Authored-By: trailers (any case)
#   - tool-generated bylines ("Generated with Claude Code", "🤖 Generated…", …)
#
# Invoked by lefthook's commit-msg hook with the message file as $1.
set -euo pipefail

msg_file="$1"

if grep -qiE '^[[:space:]]*co-authored-by:' "$msg_file"; then
  echo "commit-msg: Co-Authored-By trailers are not allowed in this repo (AGENTS.md §6)." >&2
  echo "commit-msg: remove the trailer and commit again." >&2
  exit 1
fi

if grep -qiE '^[[:space:]]*(🤖[[:space:]]*)?generated (with|by) ' "$msg_file"; then
  echo "commit-msg: tool-generated bylines ('Generated with …') are not allowed (AGENTS.md §6)." >&2
  echo "commit-msg: keep the message plain — summary line + optional 'why' body." >&2
  exit 1
fi
